Book store add order
Valdemar3X/book-store pull request #13
Opened 2024-05-20 09:21 UTC by Valdemar3X

2024-05-20 14:38 UTC, MAMentorFX requested changes

2024-05-20 14:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +    @ManyToOne (fetch = FetchType.LAZY)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-05-20 14:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/model/Order.java
> +@Where(clause = "is_deleted=false")
Use @SqlRestriction instead of @Where. @Where is depracated.
Fix in all the same cases

2024-05-20 14:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    @ToString.Exclude
use @ToString(exclude =
and @EqualsAndHashCode(exlude = 
on class level
Fix in all the same cases

2024-05-20 14:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/repository/order/OrderRepository.java
> +
```suggestion
```

2024-05-20 14:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-05-20 14:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    public void updateOrderStatus(Long id, UpdateOrderDto requestDto) {
@Transactional. You make more than one call to DB

2024-05-20 14:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-05-20 14:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +                .mapToDouble(ci ->
```suggestion
                .mapToDouble(cartItem->
```

2024-05-20 14:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        for (CartItem cartItem : cartItems) {
suggest using cartItems.forEach()

2024-05-20 18:48 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +            @RequestBody CreateOrderRequestDto requestDto) {
```suggestion
            @RequestBody @Valid CreateOrderRequestDto requestDto) {
```

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +            Pageable pageable) {
```suggestion
            @ParameterObject @PageableDefault Pageable pageable) {
```

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +            @RequestBody UpdateOrderDto requestDto) {
```suggestion
            @RequestBody @Valid UpdateOrderDto requestDto) {
```

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +            Pageable pageable) {
```suggestion
            @ParameterObject @PageableDefault Pageable pageable) {
```

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/order/CreateOrderRequestDto.java
> +public record CreateOrderRequestDto(String shippingAddress) {
Add validation: NotBlank and Size

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    @ToString.Exclude
Not fixed

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    @OneToMany(fetch = FetchType.EAGER)
Try to avoid using Eager, you can use query or EntityGraph

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/OrderItem.java
> +    @EqualsAndHashCode.Exclude
See comment above

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/OrderItem.java
> +    @OneToOne
Why do you use OneToOne?

2024-05-20 18:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartService.getShoppingCartModel(userId);
You can simplify this logic
1. Find shoppingCart
```
2. if (cart.getCartItems().isEmpty()) {
            throw new OrderProcessingException("Cart is empty for user: " + userId);
}
```
3. Order order = orderMapper.cartToOrder(cart, orderDto.shippingAddress());
4. shoppingCart.getCartItems().clear();
5. save

Where in OrderMapper
```
@Mapping(target = "id", ignore = true)
@Mapping(target = "total", source = "cart.cartItems", qualifiedByName = "total")
@Mapping(target = "orderItems", source = "cart.cartItems")
Order cartToOrder(ShoppingCart cart, String shippingAddress);
```

and 
```
@Named("total")
    default BigDecimal getTotal(Set<CartItem> cartItems) {
        return cartItems.stream()
                .map(i -> i.getBook().getPrice().multiply(BigDecimal.valueOf(i.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }
```

Also, you can initialise `Status = Status.PENDING and orderDate = LocalDateTime.now()` in Order entity

2024-05-22 12:09 UTC, Elena-Bruyako approved these changes
Good job!

2024-05-24 18:31 UTC, merged