solution
Valdemar3X/book-store pull request #17
Opened 2024-06-14 13:13 UTC by Valdemar3X

![test_covearage](https://github.com/Valdemar3X/book-store/assets/107481210/337d1ffc-7eee-4933-81d3-a324fc7cd793)

2024-06-14 16:07 UTC, Vasul-Pankiv requested changes

2024-06-14 16:07 UTC, Vasul-Pankiv commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +                .setCategories(Set.of(category));
create book provider and use it to get needed book and bookDto

2024-06-14 16:07 UTC, Vasul-Pankiv commented on src/test/java/mate/academy/bookstore/controller/CategoryControllerTest.java
> +        CategoryDto categoryDto = new CategoryDto().setName("test");
same for categories

2024-06-14 16:07 UTC, Vasul-Pankiv commented on src/test/resources/database/books/add-test-book.sql
> +INSERT INTO books (id, title, author, isbn, price) VALUES (4, 'Test', 'Test', '5555', 15)
files should end with empty files

2024-06-17 19:22 UTC, sarakhmen approved these changes

2024-06-18 06:34 UTC, merged