solution
Valdemar3X/book-store pull request #5
Opened 2024-03-29 11:04 UTC by Valdemar3X

2024-03-29 15:30 UTC, olekskov requested changes

2024-03-29 15:30 UTC, olekskov commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>      private BigDecimal price;
Please check ```@NotEmpty, @NotBlank, @ISBN, @Length``` validation annotations to make more precise validations

2024-04-01 08:59 UTC, Vasul-Pankiv requested changes

2024-04-01 08:59 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
> +    @NotEmpty
https://www.baeldung.com/java-bean-validation-not-null-empty-blank
Read about diff between notEmpty and notBlank and choose what is more suitable for your case

2024-04-01 08:59 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
> +    @NotEmpty
There is an @ISBN annotation

2024-04-01 14:07 UTC, olekskov approved these changes

2024-04-01 14:09 UTC, merged