add-roles-solution
Valdemar3X/book-store pull request #8
Opened 2024-04-16 07:25 UTC by Valdemar3X

2024-04-16 09:12 UTC, Rommelua requested changes

2024-04-16 09:12 UTC, Rommelua commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
> +                                .permitAll()
why do we need permitAll() 2 times?

2024-04-16 09:12 UTC, Rommelua commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
> +@Component
??
Service is better

2024-04-16 14:10 UTC, MAMentorFX requested changes

2024-04-16 14:10 UTC, MAMentorFX commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +                    references: roles(id)
these two columns combined need to be a primary key for this table

2024-04-16 14:10 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
>      public UserResponseDto register(UserRegistrationRequestDto request)
@Transactional. You make more than one call to DB

2024-04-16 14:10 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
> +        user.setRoles(Set.of(getUserRole(Role.RoleName.USER)));
these lines have to be done in mapStruct

2024-04-16 14:10 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/security/CustomUserDetailsService.java
> +                () -> new RuntimeException("Can't find user by email" + email));
```suggestion
                () -> new RuntimeException("Can't find user by email: " + email));
```

2024-04-16 14:26 UTC, kerrrusha requested changes

2024-04-16 14:26 UTC, kerrrusha commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +                    references: roles(id)
```suggestion
                    references: roles(id)
          primaryKey:
              columnNames: user_id, role_id
```

2024-04-17 09:09 UTC, kozhukhovsky approved these changes

2024-04-19 08:25 UTC, merged